experiment_name: 'Net3DAE_210_metric_2encoder_0decoder_10reg'

trainer: 'autoencoder'
num_epochs: 1000
batch_size: 500
log_iterations: 50
patience: 35
loss_func: NTXentAE
loss_params:
  tau: 0.1
  reconstruction_reg: 10
num_train: 50000

required_data:
  - dgl_graph
  - complete_graph3d
  - pairwise_indices
  - pairwise_distances
metrics:
  - positive_similarity
  - negative_similarity
  - contrastive_accuracy
  - true_negative_rate
  - true_positive_rate
  - uniformity
  - alignment
  - batch_variance
  - dimension_covariance
main_metric: loss
collate_function: contrastive_vae_collate

optimizer: Adam
optimizer_params:
  lr: 8.0e-5


scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  cooldown: 20
  factor: 0.6
  patience: 25
  min_lr: 1.0e-6
  threshold: 1.0e-4
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 210
  hidden_dim: 200
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.93
  readout_hidden_dim: 200
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 7
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True

# Model parameters
model3d_type: 'Net3DAE'
model3d_parameters:
  projection_dim: 70
  projection_layers: 2
  distance_net: True
  hidden_dim: 70
  hidden_edge_dim: 20
  node_wise_encoder_layers: 0
  node_wise_output_layers: 0
  message_net_layers: 1
  update_net_layers: 1
  reduce_func: 'mean'
  fourier_encodings: 4
  encoder_depth: 2
  decoder_depth: 0
  dropout: 0.0
  batch_norm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.93
  readout_aggregators:
    - min
    - max
    - mean





# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt