experiment_name: 'baseline'


dataset: qm9
num_epochs: 1000
batch_size: 128

log_iterations: 30
patience: 30
loss_func: L1Loss
num_train: 50000
targets:
  - homo

required_data:
  - pytorch_geometric_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties
collate_function: pytorch_geometric_collate

optimizer: Adam
optimizer_params:
  lr: 7.0e-5


scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'GeomolGNNWrapperOGBFeat'
model_parameters:
  target_dim: 1
  hidden_dim: 50
  readout_layers: 2
  readout_batchnorm: True
  depth: 3
  n_layers: 2



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt