experiment_name: 'baseline'

dataset: 'ogbg-molpcba'
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 40
minimum_epochs: 120
loss_func: OGBNanLabelMSELoss
required_data:
  - dgl_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr


optimizer: Adam
optimizer_params:
  lr: 1.0e-3

scheduler_step_per_batch: False
lr_scheduler: ReduceLROnPlateau
lr_scheduler_params:
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'max'
  verbose: True



# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 128
  hidden_dim: 200
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.1
  readout_hidden_dim: 200
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 7
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True





# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt