experiment_name: 'baseline'

pretrain_checkpoint: runs/PNA_qm9_NTXent_3DDepth2_123_03-09_11-45-21/best_checkpoint.pt
transfer_layers:
  - gnn


transfer_lr: 0.0
reuse_pre_train_data: True
num_epochs: 1000
batch_size: 128
log_iterations: 1
patience: 30
num_train: 50000
loss_func: MSELoss
required_data:
  - dgl_graph
  - pairwise_indices
  - pairwise_distances
metrics:
  - pearsonr
  - rsquared
  - mean_predictor_loss
collate_function: pairwise_distance_collate
main_metric: 'loss'

optimizer: Adam
optimizer_params:
  lr: 1.0e-3


model_type: 'PNADistancePredictor'
model_parameters:
  target_dim: 256
  hidden_dim: 200
  projection_dim: 100
  projection_layers: 2
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.1
  readout_hidden_dim: 200
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 7
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True




# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt