experiment_name: '3DInfoMax'

pretrain_checkpoint: runs/PNA_qm9_NTXent_3DDepth2_123_03-09_11-45-21/best_checkpoint.pt
transfer_layers:
  - mp
  - input
  - node_embedding


transfer_lr: 0.0
transfer_3d: True
reuse_pre_train_data: True
num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 30
num_train: 50000
loss_func: MSELoss
required_data:
  - complete_graph3d
  - pairwise_indices
  - pairwise_distances
metrics:
  - pearsonr
  - rsquared
  - mean_predictor_loss
collate_function: pairwise_distance_collate
main_metric: 'loss'

optimizer: Adam
optimizer_params:
  lr: 1.0e-3


# Model parameters
model_type: 'Net3DDistancePredictor'
model_parameters:
  target_dim: 256
  projection_dim: 100
  projection_layers: 2
  hidden_dim: 20
  hidden_edge_dim: 20
  node_wise_output_layers: 0
  message_net_layers: 1
  update_net_layers: 1
  reduce_func: 'mean'
  fourier_encodings: 4
  propagation_depth: 2
  dropout: 0.0
  batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.93
  readout_hidden_dim: 20
  readout_layers: 1
  readout_aggregators:
    - min
    - max
    - mean



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt