experiment_name: 'baseline'

num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 30
loss_func: L1Loss
num_train: 50000
targets:
  - homo
required_data:
  - dgl_graph
  - raw_features
  - positional_encoding
  - targets
collate_function: pna_transformer_collate
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties

optimizer: Adam
optimizer_params:
  lr: 7.0e-5


scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [3000]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



model_type: 'PNATransformer'
model_parameters:
  target_dim: 1
  hidden_dim: 200
  nhead: 10
  dim_feedforward: 200
  dropout: 0.0
  propagation_depth: 7

  readout_batchnorm: True
  readout_hidden_dim: 128
  readout_layers: 2

  mid_batch_norm: True
  last_batch_norm: True
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True





# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt