experiment_name: 'baseline_few_features'

dataset: 'ogbg-molhiv'
num_epochs: 1000
batch_size: 64
log_iterations: 30
patience: 30
loss_func: BCEWithLogitsLoss
required_data:
  - san_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr
optimizer: Adam
optimizer_params:
  lr: 1.0e-4

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [1500]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-5
  mode: 'min'
  verbose: True

model_type: 'SAN'
model_parameters:
  target_dim: 1
  in_feat_dropout: 0.0
  layer_norm: False
  batch_norm: True
  gamma: 1.0e-6
  full_graph: True
  GT_hidden_dim: 64
  GT_n_heads: 4
  GT_out_dim: 64
  GT_layers: 10
  LPE_n_heads: 4
  LPE_layers: 3
  LPE_dim: 16
  dropout: 0.01
  batch_norm_momentum: 0.1

  readout_batchnorm: True
  readout_hidden_dim: 90
  readout_layers: 2
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt