experiment_name: 'r2_rdkit_120k'

dataset: qm9_rdkit
num_epochs: 1000
batch_size: 32

log_iterations: 30
patience: 20
num_train: 50000
loss_func: L1Loss
targets:
  - r2
required_data:
  - pytorch_geometric_smp_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties
  - mean_predictor_loss
collate_function: pytorch_geometric_collate

optimizer: Adam
optimizer_params:
  lr: 0.0005

scheduler_step_per_batch: False
lr_scheduler: StepLR
lr_scheduler_params:
  step_size: 15
  gamma: 0.5

model_type: 'SMP'
model_parameters:
  target_dim: 1
  hidden_dim: 128
  use_node_features: True
  energy_and_force: False
  output_init: zeros # in DimeNet++, for QM9, 'zeros' for mu, homo, lumo, and zpve; 'GlorotOrthogonal' for alpha, R2, U0, U, H, G, and Cv
  num_spherical: 3
  num_radial: 6
  out_emb_size: 256
  basis_emb_size: 8
  int_emb_size: 64
  propagation_depth: 4
  hidden_channels: 128
  cutoff: 5.0


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt