experiment_name: 'graphormer_settings'

num_epochs: 1000
batch_size: 128

log_iterations: 50
patience: 30
num_train: 50000
loss_func: L1Loss
targets:
  - homo
required_data:
  - raw_features
  - positional_encoding
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared
  - qm9_properties
  - mean_predictor_loss
collate_function: padded_collate_positional_encoding

optimizer: AdamW
optimizer_params:
  lr: 2.0e-4

scheduler_step_per_batch: True
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [40000]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: OneCycleLR
  epochs: 200
  steps_per_epoch: 391
  anneal_strategy: 'linear'
  max_lr: 2.0e-4


model_type: 'TransformerPlain'
model_parameters:
  target_dim: 1
  hidden_dim: 512
  nhead: 32
  dim_feedforward: 512
  dropout: 0.1
  propagation_depth: 6


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt