experiment_name: 'tune'

multithreaded_seeds:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
pretrain_checkpoint: runs/OptimalTransportModel_file_loader_qm9_baseline_123_03-08_10-53-57/best_checkpoint.pt
transfer_layers:
  - gnn.
exclude_from_transfer:
  - batch_norm

dataset: 'ogbg-molesol'
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 40
loss_func: L1Loss
collate_function: pytorch_geometric_collate
required_data:
  - pytorch_geometric_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr


optimizer: Adam
optimizer_params:
  lr: 1.0e-3

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,350]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'GeomolGNNWrapperOGBFeat'
model_parameters:
  target_dim: 1
  hidden_dim: 25
  readout_layers: 2
  readout_batchnorm: True
  random_vec_std: 5.0
  random_vec_dim: 10
  gnn_params:
    hidden_dim: 25
    depth: 3
    n_layers: 2



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt