experiment_name: 'tune_drugs_NTXent_tiny_net_snapshot_energy'

pretrain_checkpoint: runs/PNA_drugs_NTXentMultiplePositives_conformer_variance_reg01_07-07_08-52-33/best_checkpoint.pt
transfer_layers:
  - gnn
exclude_from_transfer:
  - batch_norm

dataset: drugs
num_epochs: 1000
batch_size: 128

log_iterations: 30
patience: 30
loss_func: L1Loss
num_train: 120000
targets:
  - ensemblefreeenergy

required_data:
  - dgl_graph
  - targets
metrics:
  - mae_denormalized
  - pearsonr
  - rsquared

optimizer: Adam
optimizer_params:
  lr: 7.0e-5


scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,390]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 1
  hidden_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  dropout: 0.0
  propagation_depth: 6
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt