experiment_name: 'tune'

seed: 6
pretrain_checkpoint: runs/OptimalTransportModel_file_loader_qm9_PNA_10000_hidden50_depth5_123_02-08_11-36-17/best_checkpoint.pt
transfer_layers:
  - gnn.
exclude_from_transfer:
  - batch_norm

dataset: 'ogbg-molesol'
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 30
loss_func: L1Loss
collate_function: pytorch_geometric_collate
required_data:
  - pytorch_geometric_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr


optimizer: Adam
optimizer_params:
  lr: 1.0e-3

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [100,100,100]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'GeomolGNNWrapperOGBFeat'
model_parameters:
  target_dim: 1
  hidden_dim: 50
  readout_layers: 2
  readout_batchnorm: True
  gnn_params:
    hidden_dim: 50
    depth: 3
    n_layers: 2



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt