program: main_downstream.py
method: grid
metric:
  name: mean_metric
  goal: maximize
parameters:
  n-layers:
    values: [1, 2]
  hidden-dim:
    values: [32, 64, 128]
  d-rate:
    values: [0, 0.2]
  n-epochs:
    values: [150]
  datasets:
    values: [
      "LD50_Zhu",
      "Caco2_Wang",
      "Lipophilicity_AstraZeneca",
      "Solubility_AqSolDB",
      "HydrationFreeEnergy_FreeSolv",
      "PPBR_AZ",
      "VDss_Lombardo",
      "Half_Life_Obach",
      "Clearance_Hepatocyte_AZ",
      "Clearance_Microsome_AZ",
    ]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

