program: main_downstream.py
method: grid
metric:
  name: mean_metric
  goal: maximize
parameters:
  n-layers:
    values: [1, 2]
  hidden-dim:
    values: [32, 64, 128]
  d-rate:
    values: [0, 0.2]
  n-epochs:
    values: [100]
  datasets:
    values: [
        "hERG",
        "hERG_Karim",
        "AMES",
        "DILI",
        "Carcinogens_Lagunin",
        "Skin__Reaction",
        "Tox21",
        "ClinTox",
        "PAMPA_NCATS",
        "HIA_Hou",
        "Pgp_Broccatelli",
        "Bioavailability_Ma",
        "BBB_Martins",
        "CYP2C19_Veith",
        "CYP2D6_Veith",
        "CYP3A4_Veith",
        "CYP1A2_Veith",
        "CYP2C9_Veith",
        "CYP2C9_Substrate_CarbonMangels",
        "CYP2D6_Substrate_CarbonMangels",
        "CYP3A4_Substrate_CarbonMangels",
    ]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

