program: main_downstream.py
method: grid
metric:
  name: mean_roc
  goal: maximize
parameters:
  hidden-dim:
    values: [8,16,32,64]
  n-layers:
    values: [0,1,2,3,4]
  d-rate:
    values: [0,0.1,0.2]
  norm:
    values: ["layer"]
  lr:
    values: [1e-3]
  batch-size:
    values: [128]
  datasets:
    values: [
        "DILI"
      ]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

