DESCRIPTORS = [
    "usrcat",
    "electroshape",
    "usr",
    "ecfp-count",
    "ecfp",
    "estate",
    "erg",
    "rdkit",
    "topological",
    "avalon",
    "maccs",
    "atompair-count",
    "topological-count",
    "fcfp-count",
    "secfp",
    "pattern",
    "fcfp",
    "scaffoldkeys",
    # "mordred",
    "cats",
    "default",
    "gobbi",
    "pmapper",
    "cats/3D",
    "gobbi/3D",
    "pmapper/3D",
]

CONTINUOUS_DESCRIPTORS = [
    "electroshape",
    "usr",
    "usrcat",
]
