experiment_name: 'comparison_depth6_10000_samlpe'

num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 80
loss_func: L1Loss
num_train: 10000
targets:
  - homo
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
e_features:
  - 'bond-type-onehot'
  - 'stereo'
  - 'conjugated'
  - 'in-ring-edges'


required_data:
  - dgl_graph
  - targets
metrics:
  - mae_denormalized

  - rsquared
  - qm9_properties

optimizer: Adam
optimizer_params:
  lr: 5.0e-4
  weight_decay: 3.0e-7

lr_scheduler: ReduceLROnPlateau
scheduler_step_per_batch: False
lr_scheduler_params:
  factor: 0.6
  patience: 25
  min_lr: 5.0e-5
  mode: 'min'
  verbose: True

# Model parameters
model_type: 'PNA'
model_parameters:
  hidden_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  dropout: 0.0
  propagation_depth: 6
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - sum
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt