experiment_name: 'contrastive_NTXent_without_sum_aggregation'

num_epochs: 1000
batch_size: 4

log_iterations: 30
patience: 25
loss_func: NTXent
num_train: 50000
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
features3d:
  - 'constant_ones'
e_features:
  - 'bond-type-onehot'
  - 'stereo'
  - 'conjugated'
  - 'in-ring-edges'
required_data:
  - dgl_graph
  - complete_graph3d
metrics:
  - positive_similarity
  - negative_similarity
  - f1_contrastive
  - contrastive_accuracy
  - true_negative_rate
  - true_positive_rate
main_metric: loss
collate_function: random_3d_node_drop_collate

optimizer: Adam
optimizer_params:
  lr: 8.0e-5
  weight_decay: 6.0e-8

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: 700
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.6
  patience: 15
  min_lr: 5.0e-6
  mode: 'min'
  verbose: True




# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 256
  hidden_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 6
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True

# Model parameters
model3d_type: 'EGNN'
model3d_parameters:
  target_dim: 256
  hidden_dim: 128
  propagation_depth: 7
  dropout: 0.0
  readout_batchnorm: True
  readout_layers: 2
  readout_aggregators:
    - min
    - max
    - mean
  batch_norm: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt