experiment_name: 'without_self_loops'

num_epochs: 1000
batch_size: 96
log_iterations: 30
patience: 80
loss_func: MSELoss
targets:
  - homo
features:
  - atom_one_hot
required_data:
  - complete_graph
  - targets
dist_embedding: True

metrics:
  - mae_denormalized

  - rsquared
  - qm9_properties
use_edge_features: False

optimizer: Adam
optimizer_params:
  lr: 1.0e-3
  weight_decay: 1.0e-16

lr_scheduler: CosineAnnealingLR
lr_scheduler_params:
  T_max: 542000

#lr_scheduler: ReduceLROnPlateau
#scheduler_step_per_batch: False
#lr_scheduler_params:
#  factor: 0.5
#  patience: 50
#  min_lr: 1.0e-4
#  mode: 'min'
#  verbose: True

# Model parameters
model_type: 'EGNNDistEmbedding'
model_parameters:
  hidden_dim: 128
  propagation_depth: 7
  dropout: 0.0
  batch_norm: True


# continue training from checkpoint:
#checkpoint: runs/EGNN_batchnorm_02-04_16-04-30/last_checkpoint.pt