experiment_name: 'molhiv'

dataset: 'molhiv'
num_epochs: 1000
batch_size: 128
log_iterations: 30
patience: 30
loss_func: BCEWithLogitsLoss
required_data:
  - dgl_graph
  - targets
metrics:
  - ogb_molhiv
  - rsquared
  - mean_predictor_loss
main_metric: ogb_molhiv
main_metric_goal: max

collate_function: s_norm_graph_collate

optimizer: Adam
optimizer_params:
  lr: 1.0e-4

scheduler_step_per_batch: False
lr_scheduler: ReduceLROnPlateau
lr_scheduler_params:
  factor: 0.5
  patience: 25
  min_lr: 5.0e-6
  mode: 'min'
  verbose: True

model_type: 'MPNN'
model_parameters:
  target_dim: 1
  aggregation: 'sum'
  hidden_dim: 90
  last_layer_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  graph_norm: True
  readout_batchnorm: True
  edge_hidden_dim: 70
  readout_hidden_dim: 70
  readout_layers: 2
  dropout: 0.0
  in_feat_dropout: 0.0
  propagation_depth: 4
  readout_aggregators:
    - mean
    - max
    - min
    - sum
  pretrans_layers: 1
  posttrans_layers: 1
  residual: True
  gru: False


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt