experiment_name: 'all_data'

num_epochs: 1000
batch_size: 96

log_iterations: 30
patience: 50
num_train: 100000
loss_func: L1Loss
targets:
  - homo
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
required_data:
  - complete_graph
  - targets
metrics:
  - mae_denormalized

  - rsquared
  - qm9_properties
  - mean_predictor_loss

optimizer: Adam
optimizer_params:
  lr: 1.0e-3
  weight_decay: 1.0e-16

lr_scheduler: CosineAnnealingLR
lr_scheduler_params:
  T_max: 542000

# Model parameters
model_type: 'Net3D'
model_parameters:
  target_dim: 1
  hidden_dim: 128
  hidden_edge_dim: 128
  reduce_func: 'sum'
  fourier_encodings: 4
  propagation_depth: 7
  dropout: 0.0
  readout_batchnorm: True
  readout_hidden_dim: 128
  readout_layers: 2
  readout_aggregators:
    - min
    - max
    - mean
    - sum
  batch_norm: True


# continue training from checkpoint:
#checkpoint: runs/EGNN_batchnorm_02-04_16-04-30/last_checkpoint.pt