experiment_name: 'tune_tau01'

pretrain_checkpoint: runs/PNA_NTXent_0.1Tau_21-05_10-09-06/best_checkpoint.pt
transfer_layers:
  - gnn

num_epochs: 1000
batch_size: 128

log_iterations: 30
patience: 50
loss_func: L1Loss
num_train: 50000
targets:
  - homo
features:
  - 'implicit-valence'
  - 'degree'
  - 'hybridization'
  - 'chirality'
  - 'mass'
  - 'electronegativity'
  - 'aromatic-bond'
  - 'formal-charge'
  - 'radical-electron'
  - 'in-ring'
  - 'atomic-number'
e_features:
  - 'bond-type-onehot'
  - 'stereo'
  - 'conjugated'
  - 'in-ring-edges'


required_data:
  - dgl_graph
  - targets
metrics:
  - mae_denormalized

  - rsquared
  - qm9_properties

optimizer: Adam
optimizer_params:
  lr: 1.0e-4

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: 1500
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 5.0e-6
  mode: 'min'
  verbose: True


# Model parameters
model_type: 'PNAFrozen'
model_parameters:
  target_dim: 1
  hidden_dim: 90
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  readout_hidden_dim: 90
  readout_layers: 2
  dropout: 0.0
  propagation_depth: 6
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True



# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt